name: Push package to Octopus Deploy
description: 'Creates and pushes build output to Octopus Deploy for deployment.'
inputs:
  octopus-deploy-api-key:
    description: 'API key for Octopus Deploy, which should already be masked as a secret'
    required: true
  additional-metadata-paths:
    description: 'Additional metadata files that should be copied to the root of the deployment package. File patterns are supported, one pattern per line.'
    required: false
    default: ''
  perform-nuget-verify:
   description: 'A flag to indicate that the nuget signature verification step should be skipped.'
   type: boolean
   default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Install Octopus CLI
      uses: OctopusDeploy/install-octopus-cli-action@v1.2.1
      with:
        version: latest
    - name: Verify nuget package signatures
      if: ${{ inputs.perform-nuget-verify }}
      run: dotnet nuget verify nugets/
